server:
  port: 8022

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://121.187.22.37:3310/doori?serverTimezone=Asia/Seoul
    username: dbuser
    password: password!

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update #create update none

    show-sql: true
  main:
    allow-circular-references: true
  data:
    redis:
      host: 121.187.22.37
      password: mypassword
      port: 6379


    mongodb:
      host: 121.187.22.37
      port: 9999
      authentication-database: admin
      username: mongouser
      password: mypassword
      database: RUDoori

  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: guddn8405
    password: qvxqzfcywtfrqpap
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7

file:
#  serverDir: /Users/baghyeong-u/Desktop/imageFolder/
  serverDir : /home/devuser/Doori/image/
  dbDir : http://121.187.22.37:8900/image/
#  serverDir: C:\Users\paekjiyeon\Desktop\image\

jwt:
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #key size (512bit)
  # https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000	# 1 day
  refresh-expiration: 604800000 #7days

# 로그 파일의 경로와 이름을 지정
logging:

  level:
    com.knucapstone.rudoori.controller: DEBUG
